[application]
name = "social-links-replacement"
default_platform = "web"
[web.app]

# HTML title tag content
title = "GoncherGaming's Social Links"

# include `assets` in web platform
[web.resource]
assets = "assets"
# Additional CSS style files
style = ["tailwind.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

[web.watcher]
out_dir = "dist"

# Javascript code file
# serve: [dev-server] only
script = []
